"""initial_core_tables

Revision ID: ae0617ee4116
Revises: 
Create Date: 2026-03-21 10:50:14.773724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0617ee4116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('teams_count', sa.Integer(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'deleted_at', name='uq_organization_name_deleted_at')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', 'deleted_at', name='uq_team_name_org_deleted_at')
    )
    op.create_table('members',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('auth_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'auth_user_id', 'deleted_at', name='uq_member_team_user_deleted_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('teams')
    op.drop_table('organizations')
    # ### end Alembic commands ###
